molnarg/node-http2

- README.md
The old one was returning a 404 error.
> Fix GSoC 2013 URL

- README.md
- example/client.js
- lib/http.js
- test/http.js
Hi there! This is a small change that allows clients to specify self-signed certificates without disabling verification entirely.
> Forward all `Agent` options to the underlying `https.Agent`

- .travis.yml
* Enable testing on iojs and node 0.12 (since we support both)
* Stop testing on node < 0.12 (since that's no longer supported)
> Update node versions tested on CI

- lib/http.js
New Endpoints were not being added to the agent.  Every request to the origin was creating a new request. This was happening in http only
> Fix: In clear text, adding endpoint to Agent.endpoints

- lib/protocol/compressor.js
When recieving a table resize in HeaderSetDecompressor, this.setTableSizeLimit was undefined.
Now calling this._table.steSizeLimit directly.
> Fix to HeaderSetDecompressor table resize.

- lib/http.js
- test/http.js
Node does that. It is convenient.
> Add remoteAddress and remotePort to the request handler's request.socket

- lib/protocol/connection.js
I think [RFC7540](https://tools.ietf.org/html/rfc7540#section-3.5) says that a server should return PROTOCOL_ERROR if the first frame is not SETTINGS.
> Send PROTOCOL_ERROR if the first frame is not SETTINGS

- lib/http.js
- test/http.js
`listening` event is currently not forwarded which force the user to pass a callback to `.listen()`.
This breaks certain patterns such as the use of [event-to-promise](https://www.npmjs.com/package/event-to-promise).
The problem is worst for the `error` event: because it is not forwarded, it will crash the process.
> Forward `listening` and `error` events.

- lib/http.js
Allow 'te' to have value 'trailers'.
From the HTTP2.0 spec:
[https://httpwg.github.io/specs/rfc7540.html#rfc.section.8.1.2]
HTTP/2 does not use the Connection header field to indicate
connection-specific header fields; in this protocol, connection-specific
metadata is conveyed by other means. An endpoint MUST NOT generate an
HTTP/2 message containing connection-specific header fields; any message
containing connection-specific header fields MUST be treated as
malformed (Section 8.1.2.6).
> The only exception to this is the TE header field, which MAY be
> present in an HTTP/2 request; when it is, it MUST NOT contain any
> value other than "trailers".
> Update the check on deprecated headers

- lib/http.js
node-http2 behaves differently compared to the standard node http- and https-API when it comes to the return value of `Server.listen()` and `Server.on()`.
This PR adapts the behavior of the original node APIs.
> Allow chaining for Server.listen and Server.on

- lib/protocol/flow.js
Currently, the following scenario can occur
- a new connection is created; a new stream is created and a large
payload is sent on it
- the large payload exhausts its window and gets blocked
- flow._read() calls .once('window_update', this._read) to be unblocked
when a window update is received
- at this point, the window_update event from the receipt of settings
for the connection is received.  This usually won't update the window,
unless the remote window was much larger the original local window.
However, it triggers the window_update event handler that was
registered for unblocking the read
- subsequently, the when WINDOW_UPDATE that actually update the window
for stream is received, the read is no longer listening for it.
This change resolves the problem by only firing the …
> Avoid firing window_update unnecessarily.

- lib/protocol/stream.js
- test/stream.js
https://httpwg.github.io/specs/rfc7540.html#StreamStates
'WINDOW_UPDATE or RST_STREAM frames can be received in this state for a
short period after a DATA or HEADERS frame containing an END_STREAM flag
is sent.'
The current logic does not allow this work in all valid cases,
> Allow receipt of WINDOW_UPDATE on closed streams

- lib/http.js
I'm experiencing issues when using http2 with other modules that expect the same interface as the core http server. The `.address()` method seems to be the main culprit. 
Resolves #157
> Adds address function for compatibility with core http and https modules

- .npmignore
I would recommend adding a these files/dirs to the .npmignore file since they are unnecessary for the user downloading the package and they can still get these files and directories by cloning the repo.
> removing unnecessary files and directories from npm pkg

- lib/http.js
This is a reopen of PR #115 which had been closed too fast.
It fix a warning triggered by firing off more than ten requests at once.
```
warning: possible EventEmitter memory leak detected. 11 listeners added. Use
emitter.setMaxListeners() to increase limit.
```
It happens on all NodeJS versions (including latest 5.x)
> set agent max listeners to infinite

- lib/http.js
implicitHeader alias for implicitHeaders to be compatible with Node.js
> implicitHeader alias

- lib/http.js
- test/http.js
If I understand the purpose of this project correctly, one of the goals is to be 100% API compatible with the Node.js core http/https modules. 
I found a minor difference in the way that http2 handles the `Set-Cookie` header: Node core will force it to be an array even if it the HTTP response only contains a single `Set-Coolie` header ([source code](https://github.com/nodejs/node/blob/fab240a886b69ef9fa78573fc210c15cfe0018f0/lib/_http_incoming.js#L127-L133)).
This pull request tries to add the same functionality to the http2 module. It works with this PR, but I'm not entirely sure I've added the logic in the correct location as I had a hard time figuring out the structure of the source code. Please let me know if you want me to modify my pull request.
> Ensure Set-Cookie headers are always an array

- lib/http.js
Because `http`,` https` module have `response.socket` (which is the same `request.socket`).
if this module haven't `response.socket`, it will make some of the modules not work. (Like [koa/lib/response.js](https://github.com/koajs/koa/blob/master/lib/response.js#L489))
> Assign socket to response

- lib/http.js
- lib/protocol/stream.js
Methods of EventEmitters should not throw Errors but emit error events instead.
On top of being the recommended way to throw errors in EventEmitters,
this is needed to be able to handle thoose errors.
Some errors may happen randomly or may be due to external sources (server or libraries).
A typical usecase is forwarding http/2 requests and response (thoose can contains minor errors like deprecated headers or invalid frame or whatever and it should not crash the server ...)
Currently thoose errors are not catchable (because they are thrown from asynchronous or nested methods).
Emiting error event allow to handle errors (by listening to error event) while keeping the original behavior (throwing error) if error event is not listened to
This PR apply this for a few errors.
> emit error events instead of throwing Error

- lib/http.js
P.S. I'm not quite sure if this fix is complete and pervasive, but it prevents at least [one leak](https://github.com/molnarg/node-http2/blob/427e60c0255685df41090fbcf104e706b5ae08f2/lib/http.js#L993) for sure, which happens when error is emitted before the connection is established (for example, domain name can't be resolved).
> Leak less listeners on error

- lib/protocol/framer.js
Fix GOAWAY deserialization when debug data is present. Additional debug data is allowed to be included in the GOAWAY frame: https://http2.github.io/http2-spec/#GOAWAY. We now put that data into `frame.debug_data` instead of returning a FRAME_SIZE_ERROR. Fixes #218 and #219.
> GOAWAY deserialization fix

- lib/protocol/connection.js
this PR contains Clean up ended streams to free leaked memory #200 and an additional check if stream is defined. (line 314)
without these changes I was not able to run this code for a longer time. I use this in production, should be well "tested".
> memory leak fix (by argon) and another 'upstream is not defined' check

- lib/protocol/framer.js
I extended the Object prototype and ran into this issue.
> ignore inherited properties when iterating through flags
